import type { NavItem } from "../types/admin";

export const NAV_ITEMS: NavItem[] = [
  { key: "dashboard", label: "Dashboard" },
  { key: "customers", label: "Customers" },
  { key: "partners", label: "Partners" },
  { key: "helpers", label: "Technician Helpers" },
  { key: "services", label: "Services" },
  { key: "catalog", label: "Item Catalog" },
  { key: "bookings", label: "Bookings" },
  { key: "payments", label: "Payments" },
  { key: "complaints", label: "Complaints" },
  { key: "audit", label: "GST Report" },
  { key: "disputes", label: "Disputes" },
  { key: "analytics", label: "Analytics" },
  { key: "coupons", label: "Coupons" },
  { key: "referrals", label: "Referrals" },
  { key: "live-tracking", label: "Live Tracking" },
  { key: "zones", label: "Zones" },
  { key: "banners", label: "Banners" },
  { key: "offers", label: "Offers" },
  { key: "notifications", label: "Notifications" },
  { key: "roles", label: "Roles" },
  { key: "settings", label: "Settings" },
  { key: "policies", label: "About Us & Policies" },
  { key: "test-reset", label: "Test Data Reset" },
];
